
nodeLinker: node-modules

# Optional: Ensure global packages also use node_modules
enableGlobalCache: false

# Optional: Keep the classic behavior of linking dependencies
nmMode: hardlinks-local

# Optional: Disable immutable installs (useful for local development)
enableImmutableInstalls: false

# Optional: Use a specific npm registry (if needed)
npmRegistryServer: "https://registry.npmjs.org"
